### ISSUE TITLE
First feedback, questions and some suggestions to 1.0

### ISSUE THREAD

**Issue by merlinuwe** [drbap/dashboard-navigator-for-obsidian#1]
You shouldn't have shown me the link to the dashboard navigator, hehe. Here are some ideas (but I'm sure you have also good ones.)

At first: Gratulation. This is the next big thing.

Fits perfect to MagicUser theme Moon. 

Sorting of the tables by mouse-click on the headers?

Sort by: By "last accessed" possible?

At the moment, there are scrollbars. Yes, the horizontal one may appear, when there are long paths, filenames or many tags.

Recent files seems to be the same as Recent notes, at the moment. I opened a pdf-file but the recent files seem to show the same.

Optional link to start in the left ribbon

"Other" is very much. The user may see his prefered file types (.mm, excaligraph, html, ico, svg, py, gif, avif, lnk, MS Office/LibreOffice files, zip, 7z, xmind, json, ...)

![image](https://github.com/user-attachments/assets/e3eb9a5e-3a34-4e0f-a22a-851bc2bb9706)

Search: Which (fast) search engine do you use? tag:Obsidian does not work, but #Obsidian, wao!
Searching with and, or, not, filter? Is there a documentation?
Click on tag to search -> well made. (Idea: same for click on the path)

The font size could be greater for my old eyes.

Dynamical column with, very good.

Dashboard: Hover plugin support?
Cool: Searching without switching before to the Navigator. 

Well thought out.

**Comment by drbap** [comment]
First of all, thank you very much for the feedback and for testing this plugin. Much appreciated. It is still in version 1.0.0, I hope to improve it, but with a focus on speed in mind. I intend to keep it as fast as possible to find the content.

Well, I will try to comment on some of your suggestions/feedback...

> Sorting tables by mouse click on the headers?

You can sort by **double left clicking on the desired table header** (it will also toggle between ascending/descending -> sort order). I had to use this to allow easier resizing of the table column and also to avoid misclicks on the table headers.

Font size will have an option soon (plugin settings). But I will have to limit the font size maybe to 22 or 24px. I also plan to let the user show/hide specific columns, to have more screen space).

About the search, it is implemented by the plugin, it does not use Obsidian search. I tried to make it as fast as possible, so that you can quickly find the content you want. If I added too many AND | OR options, it could become slow. I tested the search on relatively large vaults with 10,000+ files and it was still fast. The plugin search does not use keywords like Obsidian search, such as `tag:tagName`. You can type `#tagName` (start with hashtag symbol and it will fetch all the notes where you find the tag. You can also use some regular expressions like `#tag1|#tag2` to see notes with tags 1 and/or tag2.

So, in general terms, you can type the word, date, folder path, `#tag` or any content displayed in the search result table. For example, start with `/FolderName/` and it will find all the files in that folder and its subfolders. You can also search by extension like `.ppt`, `.pdf` or any other file extension. You don't need to type `*.ppt` or `*.pdf`. Just type directly what you want.

About clicking on tags, yes, when you click on any tag, it will fetch all the notes with that tag (including the tags added in frontmatter).

You can right click on the search result and use the context menu to show the file properties. The properties window will show the tags in the selected file.

When possible, I will write more about the search functionality.

There is also a **date filter**... You can simply type the date like `2024-07` (depending on the selected date format), to get all notes from this month. But you can start the input search with only **special keywords** like `@day` to show notes from the same day (today). Then `day-1` (or `@yesterday`) and continue to `@day-7`, `@week`, `@month` and `@year`. These special keywords will have a different color than the traditional input text color. They will have the selected accent color.

- I plan to have the option of colored icons. I tried (file name and icon), but it seemed distracting to me (so many colors at once). Maybe only the file icon could be colored (optional).

I have added your suggestions to the list of things to consider and/or implement in future updates. If you have any more suggestions, I will be happy to hear them.

All the best

**Comment by drbap** [comment]
Some features implemented **plugin version 1.1.0**.

- New **clear input search** button.
- **Click on path** (navigator).
- **Font size control** using slider (results and links).

I hope it is easier to see now. You can select font size up to 24px using the font slider.

All the best

**Comment by merlinuwe** [comment]
Ah, the font size is now adjustable, but it affects only the first 2 columns - intended?

![image](https://github.com/user-attachments/assets/71b5973a-0d9d-4f59-b7f8-da98fff91397)

Fast searching with path, great; quick sortable columns, also great.

As far as I see no side effects, no entries in the console.

Can't wait for the next release. ;-)

**Comment by drbap** [comment]
Thanks, my friend. Glad it looks better now.

Well, no. It should increase the font size (all results and links, not only the first 2 columns). Check it out the screenshot below (please check if there is any table plugin that is using some **!important** css rule to set the font size).
![dn_font_size001](https://github.com/user-attachments/assets/3197f128-a046-4a66-87a9-19b18f0d8fa8)

Thanks for the suggestion of right align the size column. Stay tuned for the next update.

**Comment by drbap** [comment]
The screenshot is using the default theme, but it works this way using MagicUser theme as well (not only 2 columns).

**Comment by merlinuwe** [comment]
Yes, I have this css file which has `font-size: 0.8em !important;` in the 3rd last line. But when I delete !important, my dataview an markdown tables have a too wide font. Do you have any advice how I can solve this?

```css

/* Mi., 2024-07-03, 20:00:16 Uhr:  Verkleinert dataview Tabellen 
Tabellen-Schmalschrift-mit-dataview-scrollbar.css

Quelle: https://www.reddit.com/r/ObsidianMD/comments/109oojk/dataview_table_font_size/
*/

table  {
  font-variant-numeric: lining-nums tabular-nums; /* Ziffern gleich groß in Tabellen, damit sie schön untereinander stehen */
  /* Schmale Schrift für Tabellen, alle verfügbar unter Windows */
  font-family: "Roboto Condensed", "Noto Sans", "Open Sans SemiCondensed", "Open Sans Condensed", sans-serif; 
  color: lightyellow;
  margin-right: auto;
  width: 50%;
  border-collapse: collapse; /* Spalten eng aneinander legen */
  border: 1px solid #ffa500;
  word-wrap: break-word; /* Automatisches Umbrechen von Wörtern */
  hyphens: auto; /* Automatische Trennung von Wörtern */
}


/* I found the following CSS helpful 
in reducing the size pf my dataview tables inside obsidian. 
It limits the max height of the tables and adds vertical scroll bars. */

.block-language-dataview  {
  display: block;
  max-height: 800px;  /* Geändert von 400 auf 800px */
  overflow: auto;
}

.block-language-dataviewjs  {

  display: block;
  max-height: 400px;
  overflow: auto; }


/* */

/* Engere Spalten für Markdown-Tabellen in Obsidian */



table th  {
    color: orange !important;
    
}


/* Dashboard navigator: Makes all columns after the 2nd with this font size */
table td, table th  {
  padding: 2px 5px; /* Weniger Abstand innerhalb der Zellen */
  margin: 0; /* Kein Abstand um die Zellen herum */
  border: 1px solid #ddd; /* Dünne Rahmen um Zellen, optional */
  font-size: 0.8em !important;
  word-wrap: break-word; /* Automatisches Umbrechen von Wörtern */
  hyphens: auto; /* Automatische Trennung von Wörtern */
}



```

**Comment by drbap** [comment]
> Yes, I actually have this css file which has `font-size: 0.8em !important;` in the 3rd last line. But when I delete !important, my dataview an markdown tables have a too wide font. Do you have any advice how I can solve this?

Yes, please replace the part referring the dashboard navigator with the code below (the rest of the snippet could stay the same). It should fix it.

```css
table:not(#dn-table) td, table:not(#dn-table) th  {
  padding: 2px 5px; /* Weniger Abstand innerhalb der Zellen */
  margin: 0; /* Kein Abstand um die Zellen herum */
  border: 1px solid #ddd; /* Dünne Rahmen um Zellen, optional */
  font-size: 0.8em !important;
  word-wrap: break-word; /* Automatisches Umbrechen von Wörtern */
  hyphens: auto; /* Automatische Trennung von Wörtern */
}
```

Please let me know if it is working well for you.

All the best
