### ISSUE TITLE
Question: How to change the colors of all elements in this opened search panel?

### ISSUE THREAD

**Issue by merlinuwe** [drbap/dashboard-navigator-for-obsidian#14]
I'd like to change the colors of all elements in this opened search panel? It should fit the selected and adapted theme (See css below).

![image](https://github.com/user-attachments/assets/56204172-bf44-41bf-88bd-8e5afb1c583e)

Obviously, `<Ctrl-Shift-i>` does not work, because when I open it, the pull down window closes. I found a way to open the developer tools in a separate window, but that doesn't help much.

![image](https://github.com/user-attachments/assets/abc045d3-3fa9-4271-a906-16d56bf5fb4e)

The goal is to make it fit to this (oh, the content of the query has also the light blue ...)

![image](https://github.com/user-attachments/assets/45241907-1c78-473b-9c3f-44c3088e6e88)

---

Nonetheless, one day I'll switch the slow obsidian native search to this state and use your dashboard navigator plugin exclusively.

![image](https://github.com/user-attachments/assets/a136f593-01ad-4d7f-b766-c2dcef86574f)

---

Used css:

```css
/*
Sa., 2024-12-07, 19:26:42 Uhr: 
Wirkt zusammen mit dem magicuser theme
Passt sehr viele Farben im linken und rechten Panel an.
Aber auch in der Notiz.
*/


/* unklar */
/* Define the custom property */
/*
:root {
  --text-faint: yellow !important; /* yellow */
}
*/


  /* Was färbt nur die linken Begriffe im Bereich der aufklappt, 
wenn man ins Feld "Suchbegriff eingeben" klickt? */


/* unklar */
.pane-empty  {
    color: #000a2c !important;
/*color: darkgrey !important;
color: red !important; */
}


/* unklar */
.markdown-preview-section  {
    color: red;
}


/* Suchbereich "Keine Übereinstimmungen gefunden" */
.search-empty-state  {
    color: lime !important;
}

/* prefer-view: Text bei Info: "No value" wird in der Note und im rechten property pane rot */
.metadata-input-longtext:empty:before  {
    color: red !important;
}

/* Einige property *Werte* im rechten file Properties Pane hellgrün */
.mod-truncate  {  /* einige property-Texte */
    color: lightgreen !important;
}


/* Einige property *Eigenschaften* in der Note und 
im rechten property Pane orange */
.metadata-property-key-input  {
    color: orange !important;
}


/* Unklar */
.view-content  {
    background-color: #001132;
    color: white !important;
}


/* Anzahlen der verwendeten Tags im rechten Tags Panel
werden pink formatiert */
.tree-item-flair  {
    color: pink !important;
}


/* Texte im fileexplorer links?, 
Farbe der Tags im rechten Panel */
.tree-item-inner-text  {
    color: #c81c80 !important;
}


/* Notiznamen nur im Recent files (linkes Panel) bei .webp, 
"Verlinkte Erwähnungen" und "nicht verlinkte Erwähnungen" im rechten Panel Rückverweise */
.tree-item-inner  {
    color: #00b3b2;
}


/* Text "Advances Tables" im rechten Panel */
.advanced-tables-buttons>div>.title  {
    color: #00b3b2;
    text-decoration: none;
}


/* Rechtes Tags-Panel und
recently added files */
.tag-container.node-insert-event  {
    background-color: #001132 !important;
}


/* Schriftfarbe Recent files */
/*
.tree-item-nav-file,
.recent-files-file,  */
.data-link-text,
.newly-added-files-title-content {
    color: #ffffff !important;
}


/* linkes Panel, 
Hintergrundfarbe von Suche und 
Neue Dateien*/
.nav-files-container,
.search-result-container  {
    background-color: #001132;
}


/* Hintergrundfarbe der Obsidian-Suchergebnisse */
.search-result-container  {
    background-color: #001132;

}


/*
.search-info-container,
.search-results-info,  */
.workspace-leaf-content,
.workspace-sidedock-vault-profile,
.workspace-split  {
    /* background-color: #112238; 
    background-color: #001630;  */
    background-color: #002851 !important; /* Seltsam, ist dann aber vom Bildschirm abfotografiert diese Nummer: #00284d 
    Ist das die Dämpfung, die im Theme eingestellt werden kann? */
}


/* Unklar, was es ist */
.mod-left-split  {
    background-color: #002856 !important; 
}


/* Unklar, was es ist */
.vertical-tab-header  {
    padding: var(--size-4-3);
    background-color: #001d35;
    background-color: #002851;
}


/* Sorgt für den farbigen Rand um die modalen Fenster; 
Ecken sind nun eckig, damit man die Darstellungsfehler bei Rundungen nicht sieht. */
.modal  {
    
    border: 1px solid #c81c80;
    border-radius: 0px;
    /* box-shadow: 2px 2px 5px white !important; */
}


/* Community Erweiterungen Fenster */
.modal-sidebar  {
    background-color: #002851;
}


.modal-container.mod-dim .modal:has(.dn-container),
.dn-pagination  {
    width: 90%;
    max-width: 1920px;
    height: 90%;
    max-height: 1080px;
    background-color: #001d35;
    color: var(--dn-foreground-color);
}


/* Such-Eingabefeld in dashboard navigator plugin
und an anderen Stellen, an denen man etwas eingeben kann */
#dn-input-filter  {
    background-color: #000000;
}


/* Das auf cmenu basierende editing toolbar plugin 
Hintergrund-Farbe des Menüs, dass in jeder aktiven Notiz 
in der Quellcode-Ansicht und der Live-Vorschau oben eingeblendet ist */
#cMenuToolbarModalBar.cMenuToolbarTinyAesthetic  {
    background-color: #002851;
}
```
